baseURL = ''
languageCode = 'en-us'
title = 'Bernard Lodge #225'
theme = 'holy'
description = 'Bernard Lodge Website and News'
author = 'John Main'

enableInlineShortcodes = true
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
 [[menu.main]]
    identifier = "links"
    name = "Masonic Links"
    url = "/links/"
    weight = 90

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
[params]
    copyright = "John Main Designs ©"

[markup.goldmark.renderer]
unsafe = true